# Generated by Django 5.1.7 on 2025-03-21 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='column',
            name='field',
            field=models.CharField(choices=[('T', 'Text Field'), ('U', 'URL Field'), ('N', 'Number Field'), ('D', 'Decimal Field'), ('S', 'Select Field'), ('J', 'JSON Field')], max_length=30),
        ),
        migrations.AlterField(
            model_name='project',
            name='created_at',
            field=models.DateTimeField(auto_created=True, blank=True, null=True),
        ),
    ]
