# Generated by Django 5.1.7 on 2025-03-21 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_project_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='column',
            name='field',
            field=models.CharField(choices=[('T', 'Text Field'), ('U', 'URL Field'), ('N', 'Number Field'), ('D', 'Decimal Field'), ('S', 'Select Field'), ('J', 'JSON Field'), ('B', 'Boolean Field')], max_length=30),
        ),
    ]
